<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR', WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . "woo-advanced-product-information" . DIRECTORY_SEPARATOR );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_ADMIN', VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR . "admin" . DIRECTORY_SEPARATOR );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_FRONTEND', VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR . "frontend" . DIRECTORY_SEPARATOR );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_LANGUAGES', VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR . "languages" . DIRECTORY_SEPARATOR );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES', VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR . "includes" . DIRECTORY_SEPARATOR );
$plugin_url = plugins_url( '', __FILE__ );
$plugin_url = str_replace( '/includes', '', $plugin_url );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_CSS', $plugin_url . "/css/" );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_CSS_DIR', VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR . "css" . DIRECTORY_SEPARATOR );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_JS', $plugin_url . "/js/" );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_JS_DIR', VI_WC_ADVANCED_PRODUCT_INFORMATION_DIR . "js" . DIRECTORY_SEPARATOR );
define( 'VI_WC_ADVANCED_PRODUCT_INFORMATION_IMAGES', $plugin_url . "/images/" );

/*Include functions file*/
if ( is_file( VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "data.php" ) ) {
	require_once VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "data.php";
}

if ( is_file( VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "support.php" ) ) {
	require_once VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "support.php";
}

if ( is_file( VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "functions.php" ) ) {
	require_once VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "functions.php";
}

if ( is_file( VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "frontend.php" ) ) {
	require_once VI_WC_ADVANCED_PRODUCT_INFORMATION_INCLUDES . "frontend.php";
}
vi_include_folder( VI_WC_ADVANCED_PRODUCT_INFORMATION_ADMIN, 'WC_ADVANCED_PRODUCT_INFORMATION_Admin_' );

vi_include_folder( VI_WC_ADVANCED_PRODUCT_INFORMATION_FRONTEND, 'WC_ADVANCED_PRODUCT_INFORMATION_Frontend_' );
